"""Initial migration again

Revision ID: b1605372ba00
Revises: 321d0bb61565
Create Date: 2026-01-02 15:02:37.382514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b1605372ba00'
down_revision: Union[str, None] = '321d0bb61565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('party',
    sa.Column('party_date', sa.Date(), nullable=False),
    sa.Column('party_time', sa.Time(), nullable=False),
    sa.Column('invitation', sa.Text(), nullable=True),
    sa.Column('venue', sa.String(length=100), nullable=True),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('gift',
    sa.Column('gift_name', sa.String(length=100), nullable=True),
    sa.Column('price', sa.Numeric(scale=2), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('party_id', sa.Uuid(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['party.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('guest',
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('attending', sa.Boolean(), nullable=False),
    sa.Column('party_id', sa.Uuid(), nullable=False),
    sa.Column('uuid', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['party.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest')
    op.drop_table('gift')
    op.drop_table('party')
    # ### end Alembic commands ###
